spring.datasource.url=jdbc:postgresql://localhost:5432/ats_db
spring.datasource.username=ats_user
spring.datasource.password=ats_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
